site_name: "Leeroo Docs"
site_url: "https://leeroo-ai.github.io"

nav:
  - Overview: 
    - Quick Start : quick_start.md
    - Documentation : client.md

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
  icon: "https://www.leeroo.com/wp-content/uploads/2024/03/Layer_1.svg"
  logo: "https://www.leeroo.com/wp-content/uploads/2024/03/Layer_1.svg"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ "leeroo_client" ]
          
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences